deploy:
	ng build --prod --deploy-url "https://blog.c0nrad.io/sims/ramsauer-townsend/" --base-href "https://blog.c0nrad.io/sims/ramsauer-townsend/"
	mv ./dist/ramsauer-townsend/* ../docs/ramsauer-townsend/